### ISSUE TITLE
Array out of bound bug

### ISSUE THREAD

**Issue by xizheyin** [BurntSushi/regex-automata#32]
**Description**
I found a bug in this library using by fuzzing. After a series of invocations, the bug is triggered within the private function `get_cached_start_id`  by calling `regex_automata::hybrid::dfa::DFA::find_leftmost_rev_at`. The bug manifests as an array out-of-bounds issue, and it can be prevented by adding certain conditional checks in the preceding functions.

**Version**
regex-automata = "=0.2.0"

**Source Code**
```rust
fn main() {
    let _param1: usize = 0;
    let _param2: usize = 0;
    let _param8: &[u8] = &[124, 124, 123, 133, 144];
    let _param9: usize = 0;
    let _param10: usize = 0;

    println!(
        " _param1 = {:?}, _param2 = {:?}, _param8 = {:?}, _param9 = {:?}, _param10 = {:?}",
        _param1, _param2, _param8, _param9, _param10
    );

    let _local5 = if let Ok(x) = regex_automata::hybrid::dfa::DFA::always_match() {
        x
    } else {
        use std::process;
        process::exit(0);
    };

    let _local12 = regex_automata::HalfMatch::must(_param1, _param2);
    let mut _local13 = regex_automata::hybrid::dfa::Cache::new(&(_local5));

    let _local17 = regex_automata::HalfMatch::pattern(&(_local12));

    let _local20 = if let Ok(x) = regex_automata::hybrid::dfa::DFA::find_leftmost_rev_at(
        &(_local5),
        &mut (_local13),
        Some(_local17),
        _param8,
        _param9,
        _param10,
    ) {
        x
    } else {
        use std::process;
        process::exit(0);
    };
}
```

**Error Information**
```
thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 4', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/regex-automata-0.2.0/src/hybrid/dfa.rs:2472:9
```
**BackTrace**
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
   3: url::parser::Parser::parse_path
             at /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/url-2.4.0/src/parser.rs:1236:21
   4: url::parser::Parser::parse_file
             at /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/url-2.4.0/src/parser.rs:644:41
   5: url::parser::Parser::parse_url
             at /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/url-2.4.0/src/parser.rs:379:21
   6: url::ParseOptions::parse
             at /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/url-2.4.0/src/lib.rs:245:9
   7: url::Url::join
             at /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/url-2.4.0/src/lib.rs:387:9
   8: mytest::main
             at ./src/main.rs:122:13
   9: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
```

**the source code in lib where error occurs**
![image](https://github.com/BurntSushi/regex-automata/assets/62123683/f0e9da86-bd1d-41ee-b02c-74e4ef0f44bc)

**Comment by BurntSushi** [comment]
From the crate docs:

> WARNING: This 0.2 release of regex-automata was published before it was ready to unblock work elsewhere that needed some of the new APIs in this release. At the time of writing, it is strongly preferred that you continue using the [regex-automata 0.1](https://docs.rs/regex-automata/0.1/regex_automata/) release. Since this release represents an unfinished state, please do not create issues for this release unless it’s for a critical bug.
